# Generated by Django 4.2.7 on 2023-11-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aft', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
