# Generated by Django 4.2.7 on 2024-04-12 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_purchaseitem_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
