# Generated by Django 4.2.7 on 2023-11-25 20:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=17)),
                ('name', models.CharField(max_length=255, verbose_name='product_name')),
                ('code', models.CharField(max_length=255, verbose_name='product_code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('image1_url', models.URLField(blank=True, null=True)),
                ('image2_url', models.URLField(blank=True, null=True)),
                ('image3_url', models.URLField(blank=True, null=True)),
                ('image4_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=255, verbose_name='product_category')),
                ('gender', models.CharField(max_length=255, verbose_name='product_gender')),
                ('color', models.CharField(max_length=25, verbose_name='product_color')),
                ('brand', models.CharField(max_length=25, verbose_name='product_brand')),
                ('material', models.CharField(max_length=255, verbose_name='product_material')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
